services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: docvault
      POSTGRES_USER: docvault
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
  backend:
    image: backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/docvault
      SPRING_DATASOURCE_USERNAME: docvault
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}

      APP_SECURITY_SECRETKEY: ${JWT_SECRET}

      APP_FRONTEND_URL: ${FRONTEND_URL}

      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}

      GCS_CREDENTIALS_LOCATION: /run/secrets/docvault-gcs-key.json
    volumes:
    - /opt/docvault/secrets/docvault-gcs-key.json:/run/secrets/docvault-gcs-key.json:ro
volumes:
  pg-data: