spring.application.name=docvault
spring.profiles.active=dev

# Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/docvault
spring.datasource.username=postgres
spring.datasource.password=12345

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
server.servlet.context-path=/api

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog.xml