spring.application.name=docvault
spring.profiles.active=dev

# Multipart files
spring.servlet.multipart.max-file-size=4GB
spring.servlet.multipart.max-request-size=4GB
spring.servlet.multipart.file-size-threshold=0
spring.servlet.multipart.location=/tmp/docvault-multipart
server.tomcat.max-swallow-size=-1

# Local frontend url
app.frontend.url=http://localhost:4200

# Local Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/docvault
spring.datasource.username=postgres
spring.datasource.password=12345

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-message=always
server.servlet.context-path=/api

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog.xml

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.email.from=docvault27@gmail.com

# Local mail configuration
spring.mail.username=docvault27@gmail.com
spring.mail.password=fzyq rqpk efcg jgth

# Security
app.security.jwtExpirationMs=300000
app.security.jwtRefreshTokenExpiration=1000000
app.security.jwtRefreshTokenExpirationShort=86400
app.security.cookieMaxAge=2592000
app.security.jwtCookieName=docvault-jwt
app.security.jwtRefreshCookieName=docvault-jwt-refresh
app.security.secretKey=b06761e52abd996bd70f94bf47c0d52a7e19ffd437c6a4e90489b3f28151adda510f430cd668212c1a29df382276aaf4c325ea25bd584a7b8e68f3590192bf0024389b1b4e835a68dd76e4b62b6ebf40179b61af5ae54003bfee052c8de42c492a4cf5a533ce896e0cccf0ae3701942c37f836be8913e461c499604ee46e3971186df508758a19534bd26ce874832ffab01a898d816293ab889e9daaa1dda02fab3ecef30af98007e904359814169710c80058e45b662d7b65d204d0ec55a69acd4a31f453bb66d9d60503c3b2b50359ea414ad96a441f426de84c38a5befa35ed6feb089605b38833c23fcf5c33f1f24908d699566597647f1176dcf048081c
app.security.jwt.expiresInSec=600
app.activation.url=${app.frontend.url}/emailVerification
app.passwordReset.url=${app.frontend.url}/setNewPassword

# GCS
app.gcs.credentials.location=classpath:secret/docvault-gcs-key.json
app.gcs.bucket.name=doc_vault
app.gsc.buffer.storage.space=65536
app.security.jSessionIdCookieName=JSESSIONID

# Oauth2
spring.security.oauth2.client.registration.google.client-id=481528661526-tbsoj12c5sm72oghai543u5camb73681.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/api/login/oauth2/code/google

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200

# Jobs
indexer.pollDelayMs=2000
indexer.batchSize=3
indexer.lockSeconds=1800
indexer.maxAttempts=3
indexer.retryDelaySeconds=300
